### ISSUE TITLE
Improving the README

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/chrome-incognito-page#2]
Improving the documentation of this repository.

**Comment by redpfire** [comment]
Mind if i work on this?

**Comment by 0x48piraj** [comment]
It'll be great!

**Comment by redpfire** [comment]
Do you have in mind what you want in the readme?

**Comment by 0x48piraj** [comment]
A better explanation of this repository, a contribute section.

Also, can you please arrange the directory structure a little so that we can host it on github.io via `docs/` folder ?


**Proposed directory structure**

- README.md
- src/
    * chrome-incognito.html
    * static/
- docs/
     * chrome-incognito.html -> index.html
     * static/
